pid file = /run/rsyncd.pid
log file = /dev/null

[backup]
  path = /srv/rsync
  comment = web01 nightly backups
  read only = false
  list = true
  uid = root
  gid = root
  # no "auth users" => anonymous access
